# Generated by Django 5.0.1 on 2024-01-16 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_is_available_product_sale_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sale_price',
            new_name='discount_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='is_available',
            new_name='on_discount',
        ),
    ]
